### ISSUE TITLE
screen node no popup on operaGX

### ISSUE THREAD

**Issue by Ferniclestix** [zfkun/ComfyUI_zfkun#2]
hi,
love your screen share node, i think its really cool. in fact I did a tutorial on using it :D  https://youtu.be/DZ-n2izkYYI 
Unfortunately I've just updated comfyUI and the popup no longer appears when clicking share screen button. 
the clip area also appears not to function.

Fully up to date comfyUI running on operaGX

Checked on Firefox as working

**Comment by zfkun** [comment]
Have you tried to restart the system?

**Comment by zfkun** [comment]
During development, I found that if sharing is initiated and closed too frequently, there is a certain probability that chrome will not pop up the sharing confirmation pop-up.

There is not much time for in-depth analysis of this problem, the easiest way is to restart the operating system. It's not a great experience, but it works for me.

**Comment by zfkun** [comment]
Can you help me look at your log in the console？
Or try chrome to see if it's normal?

**Comment by zfkun** [comment]
i tried operaGX,
I found that there is indeed a certain compatibility problem. 
I will test and correct operaGX as soon as possible. 

Thank you for your reminder. because i usually use chrome more. operaGX has not been tested in advance. 
I am very sorry. - -!

@Ferniclestix

**Comment by zfkun** [comment]
@Ferniclestix 

the main reason for the problem is that operaGX does not have screen recording permission.
when clicking the `Start Share Screen` button, other windows or screens other than the opera browser window cannot be obtained. 

if your are mac

1. open setting window

1. find `Privacy & Security` -> `Screen Recording`
![image](https://github.com/zfkun/ComfyUI_zfkun/assets/646583/efc6c7e9-858a-420c-b389-521318bee559)

2. turn on for `Opera GX`
> make sure operagx has screen recording permissions.
![image](https://github.com/zfkun/ComfyUI_zfkun/assets/646583/335c4b78-aa2e-4114-a771-fbabbcd49f1f)

then, ShareScreen node will working after click `Start Share Screen` button

![image](https://github.com/zfkun/ComfyUI_zfkun/assets/646583/03e0e333-c02d-481f-bfbd-dc4d401a664c)


I'll also refine the code, adding friendly hints and error handling to remind users that they need to manually set system permissions when they need them.

thanks ~

**Comment by Ferniclestix** [comment]
The odd thing about it erroring in operaGX is that the previous version worked fine in operaGX. screensharing was fine. then I updated and it no longer worked. 
Ill check to see if there is some system permission that got flipped but this is me checking on two previously working computers after doing various restarts and having a previously working setup using operaGX.

It may be an issue that my mouse has intermittant left click missfires after clicking which causes instant double clicks every now and again so maybe two issues are combining to make it fail.

**Comment by zfkun** [comment]
Is your operating system MacOS?

Today I also released a simple update, adding some necessary error tips, and I suggest you try it out.

To test this out, I downloaded the brand new operaGX today, and after completing the system authorization for screen recording, everything works fine.

If it doesn't work, you can open developer tools and see if there are error messages in the console.

Or, like me, make sure there are no other custom plugins, make sure there are only a few custom plugins in comfyui, and run a test to see if it works


![image](https://github.com/zfkun/ComfyUI_zfkun/assets/646583/a794bc6d-2805-4acf-a7a8-b0f2269714c3)

![image](https://github.com/zfkun/ComfyUI_zfkun/assets/646583/1e9490ea-22ff-4ef3-ad34-12e0402b1422)

![image](https://github.com/zfkun/ComfyUI_zfkun/assets/646583/491a2ed2-afe1-4b1c-9838-cadb08038954)

![image](https://github.com/zfkun/ComfyUI_zfkun/assets/646583/236dd33b-3d72-4c41-808a-50d6284ded20)

**Comment by Ferniclestix** [comment]
I use windows, update fixed it, thanks :D 
also have a new mouse so single clicking for sure lol.
